---
Name: passkey-routes
After: 'framework/routes#coreroutes'
---
SilverStripe\Control\Director:
  rules:
    'passkey-auth//$Action/$ID/$OtherID': 'GienieLab\PasskeyAuth\Controller\PasskeyAuthController'
    'passkey-debug': 'GienieLab\PasskeyAuth\Controller\PasskeyDebugPageController'
    'passkey-management': 'GienieLab\PasskeyAuth\Controller\PasskeyManagementController'
